### ISSUE TITLE
Improve feedback for invalid task submission

### ISSUE THREAD

**Issue by manthey** [girder/slicer_cli_web#114]
Currently, we print an error message mentioning which fields didn't validate.  It would be nice to also mark them with css in some way that is obvious (not just color of text).

**Comment by BryonLewis** [comment]
Adding in a Bootstrap glyph icon to indicate the that the labels of parameter are wrong. 
![image](https://user-images.githubusercontent.com/61746913/75897735-0a5efa00-5e07-11ea-8bfb-e670881adb1c.png)
Also changing the placeholder background for input file fields and input text fields to the standard bootstrap alert red color.

If there is no label for the group, it will add an indication to each individual item:
![image](https://user-images.githubusercontent.com/61746913/75898906-c5d45e00-5e08-11ea-9eb9-36c94269440b.png)

**Comment by manthey** [comment]
Excellent.  It is good to have both the icon and the color feedback.

How does a check box fail to validate, though?

**Comment by BryonLewis** [comment]
I don't know all of the specific use cases.  I just noticed that the compiled output of girder references the "has-error" styling with all of the following:
![image](https://user-images.githubusercontent.com/61746913/75903913-49de1400-5e10-11ea-9bbc-bb92eba0a7c9.png)
This is most likely the default Bootstrap styling that has support for them, as well a has-success and has-warning classes.

The one instance which might not make sense right now is if there are numerous check boxes used to define settings and they conflict with each other.  I would argue that's horrible UX and that the list of options should change state (enabled/disabled) or even hide as you choose other items which should limit your choices.
