### ISSUE TITLE
Installation instructions are missing

### ISSUE THREAD

**Issue by fedorov** [girder/slicer_cli_web#19]
I would like to install this plugin as a prerequisite for HistomicsTK.

I am unable to install VirtualBox per instructions on my CentOS 6 system (not sure how to resolve the missing dependencies for the RPM package), but I installed the other 2 prerequisite packages and girder.

How do I install this plugin?

**Comment by jcfr** [comment]
Thanks for the report.

The easiest way to get HistomicsTk is to follow the vagrant instruction reported on readthedocs ? See https://histomicstk.readthedocs.io/en/latest/installation.html#installing-histomicstk-as-a-server-side-girder-plugin-using-vagrant

Calling `vagrant up` will takes care of installing all dependencies specified in the different ansible scripts.

That said, if you would like to install the plugins and dependencies in your own environment, you can look at the corresponding script. For example, [here](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/ansible/roles/girder/tasks/main.yml) is the girder role.

**Comment by jcfr** [comment]
> unable to install VirtualBox per instructions on my CentOS 6 system 

I suggest to address this first, that will allow you to more easily get the full system going.

**Comment by manthey** [comment]
Resolved by #101.
