### ISSUE TITLE
Distinguish between items and files

### ISSUE THREAD

**Issue by manthey** [girder/slicer_cli_web#45]
Currently, if we ask for a file, we actually select a Girder item.  I think these should be distinct: a consumer of the CLI might want an item or might want a file.  When we use the hierarchy widget, we can always select an item, but if a file was requested, we could return the first file within that item.  Ideally, on items that have no files we wouldn't list them, and on items that have multiple files we would allow a specific file to be selected.

**Comment by manthey** [comment]
Currently, the slicer_cli_web code has issues with the 'file' data type -- in some places we expect it to be a Girder item and in others a file.

There are two possible fixes: (1) make it so 'file' always means a Girder item.  (2) support both 'file' and 'item' as separate data types.

Neither of these changes is difficult.  (1) will always leave some confusion about what is being requested. 
 (2) is a bigger conceptual shift, and would ideally add a widget to select a file from a multiple-file item.

The choice may impact what is done in item_tasks in Girder.  @zachmullen, Do you have any opinion on which would be better?  For purposes in using this in another project (HistomicsTK), either option works (I've tested them both).

**Comment by jbeezley** [comment]
I think file and item should be different data types.  The treeview widget will be able handle the use case better than the current browser widget.

**Comment by manthey** [comment]
Resolved in PR #47.
