### ISSUE TITLE
Move in front-end CLI widget generation code from HistomicsTK

### ISSUE THREAD

**Issue by cdeepakroy** [girder/slicer_cli_web#5]
This issue involves moving the javascript code that generates the front-end widgets for slicer CLIs embedded in docker images from HistomicsTK to this repo so it can be used by other projects.

CC: @jbeezley, @manthey

**Comment by jbeezley** [comment]
Doing this would be a good opportunity to migrate to the webpack infrastructure coming in girder 2.0.  Is there an immediate need for this in girder 1.x deployments, or can it wait for other plugins to transition to 2.0 as well?

**Comment by cdeepakroy** [comment]
@jbeezley When is girder 2.0 scheduled? Once this repo is complete, then we can advertise it to be used by other projects.

**Comment by jbeezley** [comment]
It's getting close.  I think the major issue is that if I target this at 2.0, anybody who wants to use it will need to port to 2.0 as well.  On the other hand, the migration will be necessary eventually anyway.  If this is necessary within the next month (give or take), then we might consider targeting this for 1.x then porting to 2.0 later.

**Comment by jcfr** [comment]
> anybody who wants to use it will need to port to 2.0 as well
If all current user are Kitware projects, targeting 2.0 is reasonable

> we might consider targeting this for 1.x then porting to 2.0 later.
Otherwise this would also work.

**Comment by dzenanz** [comment]
@zachmullen @jbeezley PET/CT calibration project could benefit from this.

**Comment by jbeezley** [comment]
Okay, I think I'll go ahead and target 1.x for the moment, and we'll tackle 2.0 when it comes out.

**Comment by jbeezley** [comment]
Done in #15
