### ISSUE TITLE
Item selector widget grammar

### ISSUE THREAD

**Issue by manthey** [girder/slicer_cli_web#67]
If the type used in the item selector widget starts with a vowel, the text is wrong.  For instance, `Select a image for "Input Image"` should be `Select an image for "Input Image"`.  `web_client/templates/itemSelectorWidget.pug` needs to be changed.

**Comment by sgratzl** [comment]
should already be fixed: 

https://github.com/girder/slicer_cli_web/blob/03ff5bda36902bc87420b896cc445ba7249ea486/slicer_cli_web/web_client/templates/itemSelectorWidget.pug#L7-L13
