### ISSUE TITLE
Publish to pypi as part of CI 

### ISSUE THREAD

**Issue by manthey** [girder/slicer_cli_web#73]
Whenever we merge to master or tag a branch, we should publish to pypi.

We probably want the name on pypi to include girder (e.g., girder-slicer-cli-web, rather than just slicer-cli-web).

**Comment by sgratzl** [comment]
requires that the cirecleci job has the proper credentials for pypi

**Comment by manthey** [comment]
I've added credentials to publish to test.pypi.org.  When we are happy with that, I'll switch to use actual pypi.org
