### ISSUE TITLE
Pull docker images to girder worker if not present

### ISSUE THREAD

**Issue by manthey** [girder/slicer_cli_web#74]
When we import a docker image, if the specified image is not present, we pull it to the Girder machine so we can query the cli.  However, since Girder Worker could be on a different machine, the image isn't necessarily present there.  When the task is run, if the image is not present, we should pull it on Girder Worker.

**Comment by sgratzl** [comment]
in the end it is just changing: 

https://github.com/girder/slicer_cli_web/blob/e94769f8c73063c45e40b7ddfb550a2711da7c3e/slicer_cli_web/rest_slicer_cli.py#L204

however, if the user used the `latest` tag it can happen that a newer version will be pulled than the one imported.

**Comment by manthey** [comment]
Similarly, if the image was local (not pulled from Docker Hub), this may not work.

We may want to always pull by hash value rather than tag, since then it would error instead of using a unexpected image version.
