### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by manthey** [girder/slicer_cli_web#76]
Describe the capabilities of this plugin in the README file.

Add links to the xml schema that we use.  Document any modifications and alternatives (when issues such as #75 and #69 are addressed).

**Comment by sgratzl** [comment]
I haven't seen any XSD file, just this https://www.slicer.org/wiki/Documentation/Nightly/Developers/SlicerExecutionModel

**Comment by manthey** [comment]
I think 3D Slicer just uses CommonTK's CLI spec: http://www.commontk.org/index.php/Documentation/Command_Line_Interface and http://www.commontk.org/docs/html/ctkCmdLineModule.xsd
