### ISSUE TITLE
Task item location independence

### ISSUE THREAD

**Issue by manthey** [girder/slicer_cli_web#85]
Currently, if an item is moved from its parent folder, it no longer is detected as a task.

If an item is moved from its parent folder, it would not be updated on reimporting the docker image.

after a discussion we came up with the following strategy
 * [x] make items independent of where they are, so no parent-child relationship anymore
 * [x] when updating an image, store them in the regular structure, don't consider/update moved items
 * [x] rest items are created for all items independent of their location
 * [x] it can happen that now two items with the same API endpoint would exist. Thus, for each task there is one `/task/<itemid>` version and a generic `/task/` version which uses the newest item (by creation date)
 * [x] the use should use `/task/<itemid>` is version when possible
 * [x] the list function allows to specify a base folder and it will return a flat list of all contained tasks in this folder (or one of its subfolders aka `<base>/**/*.task`). By default it returns all tasks independent of their location

**Comment by sgratzl** [comment]
the reason why it is not longer detected as a task is that the parent (tag) contain meta data (in this case the `slicerCLIRestPath`) to be able to run the task

similarly for the server when generating the REST Api it takes the parent folder (e.g. for the image digest) and looks for tasks in their children. 

if we want to decouple image/tag and task from each other it requires that each task is self contained when it comes to e.g. image digest, rest path, ...

**Comment by sgratzl** [comment]
after a discussion we came up with the following strategy
 * [ ] make items independent of where they are, so no parent-child relationship anymore
 * [ ] when updating an image, store them in the regular structure, don't consider/update moved items
 * [ ] rest items are created for all items independent of their location
 * [ ] it can happen that now two items with the same API endpoint would exist. Thus, for each task there is one `/task/<itemid>` version and a generic `/task/` version which uses the newest item (by creation date)
 * [ ] the use should use `/task/<itemid>` is version when possible
