### ISSUE TITLE
Enable slicer CLIs to report progress 

### ISSUE THREAD

**Issue by cdeepakroy** [girder/slicer_cli_web#9]
This issue involves implementing the infrastructure necessary to enable slicer CLIs (within docker containers) to report progress when run via the automatically generated REST interface.

[Here](https://www.slicer.org/slicerWiki/index.php/Slicer3:Execution_Model_Documentation#Showing_Progress_in_an_Application) is a description of how Slicer tracks and shows progress of the CLIs within Slicer. 
We should probably use the same protocol if we can so the CLIs can report progress both when they are run from slicer and through the REST interface. 

Also, it would make things easier for CLI developers if we have a class with a `report()` function like [this](https://github.com/KitwareMedical/TubeTK/blob/master/Applications/ConvertTubesToImage/ConvertTubesToImage.cxx#L82) to report progress that dumps the xml to the command line or a pipe. That class should probably reside in [ctk_cli](https://github.com/commontk/ctk-cli).

**Comment by cdeepakroy** [comment]
CC: @jcfr

**Comment by zachmullen** [comment]
We'll probably want to add a new class of output handler to the girder_worker specifically for progress. We can already use an indefinite number of named pipes to have separate output channels, but I'm not sure how friendly that is for the underlying algorithms to use, since they'd have to open the named pipe as a file handle internally and call `flush` on data written to it.

**Comment by cdeepakroy** [comment]
We can add a helper class in ctk_cli similar to the one in [TubeTK](https://github.com/KitwareMedical/TubeTK/blob/25317fb8506f8cbaa2943d3e6050765c3a2e2db9/Base/CLI/tubeCLIProgressReporter.h) that could be used similar to this [example](https://github.com/KitwareMedical/TubeTK/blob/master/Applications/ConvertTubesToImage/ConvertTubesToImage.cxx#L55-L60). That helper class could encapsulate write the xml to the pipe or anything else that is needed to report progress.

**Comment by jcfr** [comment]
> add a helper class in ctk_cli similar

:+1:

**Comment by manthey** [comment]
Added in #145.
